# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Jarvisui(object):
    def setupUi(self, Jarvisui):
        Jarvisui.setObjectName("Jarvisui")
        Jarvisui.resize(1366, 720)
        self.centralwidget = QtWidgets.QWidget(parent=Jarvisui)
        self.centralwidget.setObjectName("centralwidget")
        self.background_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.background_1.setGeometry(QtCore.QRect(0, 0, 1371, 721))
        self.background_1.setText("")
        self.background_1.setPixmap(QtGui.QPixmap("Downloads/jarvis_materials/drive-download-20230414T100055Z-001/B.G/Black_Template.jpg"))
        self.background_1.setScaledContents(True)
        self.background_1.setObjectName("background_1")
        self.gif_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(420, 230, 391, 241))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("Downloads/jarvis_materials/drive-download-20230414T100055Z-001/ExtraGui/Jarvis_Gui (1).gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(1210, 0, 151, 121))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("Downloads/jarvis_materials/drive-download-20230414T100055Z-001/ExtraGui/Earth.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(10, 510, 301, 161))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("Downloads/jarvis_materials/drive-download-20230414T100055Z-001/ExtraGui/Code_Template.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.gif_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(430, 20, 351, 121))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("Downloads/jarvis_materials/drive-download-20230414T100055Z-001/ExtraGui/initial.gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.time = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.time.setGeometry(QtCore.QRect(1060, 640, 201, 51))
        self.time.setStyleSheet("background-color:Transparent;\n"
"border-color: rgb(242, 251, 255);")
        self.time.setObjectName("time")
        self.background_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.background_2.setGeometry(QtCore.QRect(1000, 500, 351, 211))
        self.background_2.setText("")
        self.background_2.setPixmap(QtGui.QPixmap("Downloads/jarvis_materials/drive-download-20230414T100055Z-001/B.G/gyhf.jpg"))
        self.background_2.setScaledContents(True)
        self.background_2.setObjectName("background_2")
        self.Date = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Date.setGeometry(QtCore.QRect(1050, 530, 221, 51))
        self.Date.setStyleSheet("background-color:Transparent;\n"
"border-color: rgb(242, 251, 255);")
        self.Date.setObjectName("Date")
        self.Start_Push_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Start_Push_Button.setGeometry(QtCore.QRect(1170, 190, 161, 61))
        self.Start_Push_Button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 234, 255);")
        self.Start_Push_Button.setObjectName("Start_Push_Button")
        self.Stop_Push_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Stop_Push_Button.setGeometry(QtCore.QRect(1170, 270, 161, 61))
        self.Stop_Push_Button.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 234, 255);")
        self.Stop_Push_Button.setObjectName("Stop_Push_Button")
        Jarvisui.setCentralWidget(self.centralwidget)

        self.retranslateUi(Jarvisui)
        QtCore.QMetaObject.connectSlotsByName(Jarvisui)

    def retranslateUi(self, Jarvisui):
        _translate = QtCore.QCoreApplication.translate
        Jarvisui.setWindowTitle(_translate("Jarvisui", "MainWindow"))
        self.Start_Push_Button.setText(_translate("Jarvisui", "START"))
        self.Stop_Push_Button.setText(_translate("Jarvisui", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvisui = QtWidgets.QMainWindow()
    ui = Ui_Jarvisui()
    ui.setupUi(Jarvisui)
    Jarvisui.show()
    sys.exit(app.exec())
